### ISSUE TITLE
[BUG] error: spawn /usr/bin/python enoent

### ISSUE THREAD

**Issue by r3pij** [Yeraze/meshmonitor#1170]
When trying to run the script (PirateWeather.py) i see - error: spawn /usr/bin/python enoent
Meshmonitor launched in docker compose

**Comment by Yeraze** [comment]
please follow the template
* provide docker-compose
* see this error where? in the UI? in the logs?
* where did you get this script from?

**Comment by Yeraze** [comment]
closing due to insufficient information.. Will re-open when/if provided.

**Comment by r3pij** [comment]
1) Docker compose version 5.0.0

1.a) docker-compose.yml

services:
  meshmonitor:
    image: ghcr.io/yeraze/meshmonitor:latest
    container_name: meshmonitor
    ports:
      - "8080:3001"
    restart: unless-stopped
    volumes:
      - meshmonitor-data:/data
    env_file: .env
    environment:
      - NODE_ENV=development
      - TZ=America/New_York
      - MESHTASTIC_NODE_IP=192.168.1.73
      - ALLOWED_ORIGINS=http://localhost:8080

volumes:
  meshmonitor-data:
    driver: local

2) See at UI.

![Image](https://github.com/user-attachments/assets/67c9d0d1-89dd-425b-9a68-c87a157ba997)

3) Script from User Scripts Gallery

![Image](https://github.com/user-attachments/assets/d1c69320-3049-4c7e-abdb-794d9746d0a2)

4) Occurs when i press the "Test" button

**Comment by Yeraze** [comment]
I think you need to set the {location} parameter on the script, per it's installation instructions.

<img width="2552" height="1256" alt="Image" src="https://github.com/user-attachments/assets/5f572f4c-9a02-47ea-9a4e-20af3b4155f9" />

**Comment by r3pij** [comment]
> I think you need to set the {location} parameter on the script, per it's installation instructions.
> 
> <img alt="Image" width="2000" height="1256" src="https://private-user-images.githubusercontent.com/5789309/528998799-5f572f4c-9a02-47ea-9a4e-20af3b4155f9.png?jwt=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3NjYzNTU2MzMsIm5iZiI6MTc2NjM1NTMzMywicGF0aCI6Ii81Nzg5MzA5LzUyODk5ODc5OS01ZjU3MmY0Yy05YTAyLTQ3ZWEtOWE0ZS0yMGFmM2I0MTU1ZjkucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI1MTIyMSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNTEyMjFUMjIxNTMzWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MzEwNjhlYmE4ZTQwMmJhM2JhYmRjMmFmMThhMTIyMzcyMjFmN2Y1Y2Q0NzljZjJiMmYwZTRjYzllYzA0MmFlZiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.cnHt3Po6mr6rYbYHeMvbn_d3vsFrY83kAYUwyl6VfRU">

The script was installed according to the installation instructions. All Python scripts don't work. JavaScript scripts work.

**Comment by r3pij** [comment]
What operating system are you using? I use Raspbian trixie. The problem still exists.

**Comment by Yeraze** [comment]
I think I fixed the issue last night, should be in today's release.

**Comment by r3pij** [comment]
Release update. I launched "docker compose pull" and restarted the container. It still doesn't work.
